site :opscode

cookbook 'apt'
cookbook 'postfix'
cookbook 'idt_infra_tools', git: 'git://github.com/tarzan0820/chef-idt-infrac-common.git'
cookbook 'python'
cookbook 'build-essential'
cookbook 'openssl'
cookbook 'xfs'
cookbook 'aws'
cookbook 'gunicorn'
cookbook 'nginx'
cookbook 'supervisor'
cookbook 'chef-ec2-ebs-snapshot', git: 'git://github.com/tarzan0820/chef-ec2-consistent-snapshot.git'
cookbook 'postfix-ses', git: 'git://github.com/tarzan0820/chef-postfix-ses.git'
